sudo: false
language: ruby
rvm:
  - 2.1
gemfile:
  - Gemfile-Travis
script:
  - bundle exec jekyll build
  - bundle exec htmlproofer ./_site --only-4xx --allow-hash-href --check-html # --check-favicon
env:
  global:
    - NOKOGIRI_USE_SYSTEM_LIBRARIES=true # speeds up installation of html-proofer
