title: ThalesVB
description: >
  Attic of random information, personal thoughts, but most of time just a live crash test site for Web Frameworks.

exclude: ['jekyll',
          vendor] # speed up Travis

plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-gist
  - jekyll-remote-theme
  - jekyll-seo-tag

baseurl: "/"
cdn_url: "//github.com/thalesvb/thalesvb.github.io/wiki/"

permalink: "/blog/:year/:month/:day/:title.html"
paginate: 5
paginate_path: "/blog/page/:num"

img_dir: "/img"
dir_blog_resources: "/blog/resources/"

gist:
  noscript: false # don't render noscript fallback tags with gist code

remote_theme: thalesvb/square-root-beer-jekyll@prologue

collections:
  projects:
    label_pretty: Projects
    icon: assignment
    output: true
    permalink: "/:collection/:name/"

defaults:
  - scope:
      type: "posts"
    values:
      layout: "post"
  - scope:
      type: "projects"
    values:
      layout: "antiheroic"

sass:
  style: compressed

root_beer:
  blog_listing_root: /blog/
  date_format: "%b %-d, %Y"
  latest_posts_limit: 3
  social_links:
    devto: thalesvb
    github: thalesvb
    linkedin: thalesvb
  analytics:
    google: UA-75600605-1

webmaster_verifications:
  google: YjSeoUocDzP9hQbZql1oadvwnIcMCimBjo6c7au_MME