# https://www.sylvaindurand.org/making-jekyll-multilingual/

exclude: ['jekyll',
          vendor] # speed up Travis

gems: [jekyll-sitemap,
       jekyll-paginate,
       jekyll-gist]

permalink: "/blog/:year/:month/:day/:title.html"
paginate: 10
paginate_path: "/blog/page/:num"

img_dir: "/img"
prefix_cdn : "//github.com/thalesvb/thalesvb.github.io/wiki"
dir_blog_resources: "/blog/resources/"

gist:
  noscript: false # don't render noscript fallback tags with gist code

collections:
  abouts:
    output: true
    permalink: "/about/:name/"
  projects:
    output: true
    permalink: "/:collection/:name/"

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: "posts"
  -
    scope:
      path: "_posts/en"
    values:
      lang: "en"
  -
    scope:
      path: "_posts/pt-BR"
    values:
      lang: "pt-br"
  -
    scope:
      path: "_projects"
      type: "projects"
    values:
      layout: "project"
  -
    scope:
      path: "_abouts"
      type: "abouts"
    values:
      layout: "default"
